In [335]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import sys
import timeit
import heapq 

In [336]:
resultA = []
resultB = []

In [337]:
class Graph():
    
    def __init__(self, vertices):
        self.V = vertices
        self.matrixgraph = []
        self.listgraph = {}
    
    def generateNew(self):
        self.matrixgraph = np.random.randint(0,11, (self.V, self.V)) #Generate random adj matrix + set limit of weights
        
        for i in range(self.V):                                     #Set diagonal of adj matrix to 0, this is to eliminate loops
            for j in range(self.V):
                if i == j:
                    self.matrixgraph[i][j] = 0
                    
        for i in range(2, self.V):               # Assumes that node 0 is our source node, eliminates all other edges except
            self.matrixgraph[0][i] = 0           # the edge from node 0 -> node 1.
        for i in range(1, self.V):
            self.matrixgraph[i][0] = 0
        
        if self.matrixgraph[0][1] == 0:          # Incase of bad RNG, form connection from source to node 1
            self.matrixgraph[0][1] = 1
            
        self.convertToAdj()                                         #Convert from Adj matrix to Adj list
                    
    def getMatrix(self):                                            #Prints the adj matrix
        print("Adjacency Matrix for the graph,")
        print(g.matrixgraph)
    
    def getList(self):                                              #Prints the adj list
        print("Adjacency List for the graph,")
        for nodes in self.listgraph:
            print(nodes, end = "")
            for edges in self.listgraph[nodes]:
                print(" -> ", edges[0], "Weight:", edges[1], end = "")
            print()
            
    def visualize(self):                                            #Visualize the graph
        G = nx.from_numpy_matrix(np.matrix(g.matrixgraph), create_using=nx.DiGraph)
        layout = nx.spring_layout(G)
        nx.draw(G, layout, with_labels=True)
        labels = nx.get_edge_attributes(G, "weight")
        nx.draw_networkx_edge_labels(G, pos=layout, edge_labels=labels)
        plt.show()
        
    def convertToAdj(self):
        for i in range(self.V):                                     #Creation of adj list using adj matrix
            self.listgraph[i] = []
        for i in range(self.V):
            for j in range(self.V):
                if self.matrixgraph[i][j] != 0:
                    temp = [j, self.matrixgraph[i][j]]
                    self.listgraph[i].append(temp)

In [ ]:
g = Graph(60)
g.generateNew()
# g.matrixgraph = [[0,1,0,0,0],
#                  [0,0,2,0,0],
#                  [0,0,0,3,0],
#                  [0,0,0,0,4],
#                  [0,0,0,0,0]]
g.getMatrix()
print()
g.getList()
print()
g.visualize()

Adjacency Matrix for the graph,
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 2 6 4]
 [0 9 0 ... 0 1 8]
 ...
 [0 7 0 ... 0 5 7]
 [0 2 8 ... 8 0 6]
 [0 5 0 ... 7 5 0]]

Adjacency List for the graph,
0 ->  1 Weight: 1
1 ->  3 Weight: 7 ->  4 Weight: 9 ->  5 Weight: 6 ->  6 Weight: 10 ->  7 Weight: 6 ->  8 Weight: 2 ->  9 Weight: 5 ->  10 Weight: 1 ->  11 Weight: 10 ->  12 Weight: 1 ->  13 Weight: 9 ->  14 Weight: 5 ->  15 Weight: 6 ->  16 Weight: 5 ->  17 Weight: 3 ->  18 Weight: 2 ->  19 Weight: 5 ->  20 Weight: 10 ->  21 Weight: 4 ->  22 Weight: 7 ->  23 Weight: 2 ->  24 Weight: 3 ->  25 Weight: 4 ->  26 Weight: 4 ->  27 Weight: 5 ->  28 Weight: 5 ->  29 Weight: 5 ->  30 Weight: 5 ->  31 Weight: 9 ->  32 Weight: 8 ->  33 Weight: 10 ->  34 Weight: 7 ->  35 Weight: 8 ->  36 Weight: 6 ->  37 Weight: 9 ->  38 Weight: 9 ->  39 Weight: 6 ->  42 Weight: 10 ->  43 Weight: 8 ->  45 Weight: 9 ->  47 Weight: 9 ->  48 Weight: 2 ->  49 Weight: 1 ->  50 Weight: 10 ->  51 Weight: 7 ->  52 Weight: 7 ->  53 Weight: 7

13 ->  1 Weight: 6 ->  2 Weight: 7 ->  3 Weight: 2 ->  4 Weight: 3 ->  5 Weight: 1 ->  6 Weight: 1 ->  7 Weight: 3 ->  8 Weight: 7 ->  9 Weight: 5 ->  10 Weight: 7 ->  11 Weight: 1 ->  12 Weight: 1 ->  14 Weight: 10 ->  15 Weight: 9 ->  16 Weight: 7 ->  17 Weight: 1 ->  18 Weight: 9 ->  19 Weight: 10 ->  20 Weight: 5 ->  21 Weight: 1 ->  22 Weight: 1 ->  23 Weight: 6 ->  24 Weight: 5 ->  25 Weight: 1 ->  26 Weight: 1 ->  28 Weight: 6 ->  29 Weight: 7 ->  30 Weight: 7 ->  31 Weight: 2 ->  32 Weight: 1 ->  33 Weight: 4 ->  34 Weight: 9 ->  35 Weight: 9 ->  36 Weight: 9 ->  37 Weight: 5 ->  38 Weight: 10 ->  39 Weight: 6 ->  40 Weight: 6 ->  41 Weight: 9 ->  42 Weight: 8 ->  43 Weight: 6 ->  44 Weight: 6 ->  45 Weight: 10 ->  46 Weight: 9 ->  47 Weight: 5 ->  48 Weight: 9 ->  49 Weight: 4 ->  50 Weight: 4 ->  51 Weight: 10 ->  52 Weight: 6 ->  53 Weight: 7 ->  54 Weight: 7 ->  55 Weight: 10 ->  56 Weight: 10 ->  57 Weight: 5 ->  58 Weight: 3 ->  59 Weight: 5
14 ->  1 Weight: 8 ->  2 Weigh

25 ->  1 Weight: 3 ->  2 Weight: 7 ->  3 Weight: 9 ->  4 Weight: 9 ->  5 Weight: 4 ->  6 Weight: 3 ->  7 Weight: 10 ->  8 Weight: 1 ->  9 Weight: 2 ->  10 Weight: 2 ->  11 Weight: 1 ->  12 Weight: 5 ->  13 Weight: 10 ->  14 Weight: 1 ->  15 Weight: 8 ->  16 Weight: 5 ->  17 Weight: 4 ->  18 Weight: 5 ->  19 Weight: 5 ->  20 Weight: 10 ->  21 Weight: 3 ->  22 Weight: 3 ->  23 Weight: 5 ->  24 Weight: 8 ->  26 Weight: 10 ->  27 Weight: 6 ->  28 Weight: 3 ->  29 Weight: 1 ->  30 Weight: 3 ->  31 Weight: 3 ->  32 Weight: 4 ->  33 Weight: 7 ->  34 Weight: 2 ->  35 Weight: 9 ->  36 Weight: 7 ->  37 Weight: 4 ->  38 Weight: 1 ->  39 Weight: 7 ->  40 Weight: 6 ->  41 Weight: 6 ->  42 Weight: 10 ->  43 Weight: 6 ->  44 Weight: 5 ->  46 Weight: 3 ->  47 Weight: 5 ->  49 Weight: 1 ->  50 Weight: 6 ->  51 Weight: 9 ->  52 Weight: 8 ->  53 Weight: 8 ->  54 Weight: 5 ->  55 Weight: 10 ->  56 Weight: 3 ->  57 Weight: 1 ->  58 Weight: 10 ->  59 Weight: 10
26 ->  1 Weight: 10 ->  2 Weight: 2 ->  4 Weig

35 ->  1 Weight: 5 ->  2 Weight: 2 ->  3 Weight: 3 ->  4 Weight: 10 ->  5 Weight: 4 ->  6 Weight: 1 ->  7 Weight: 5 ->  8 Weight: 9 ->  9 Weight: 9 ->  10 Weight: 4 ->  11 Weight: 9 ->  12 Weight: 2 ->  13 Weight: 4 ->  14 Weight: 10 ->  15 Weight: 8 ->  16 Weight: 4 ->  17 Weight: 5 ->  18 Weight: 8 ->  19 Weight: 7 ->  20 Weight: 3 ->  21 Weight: 3 ->  22 Weight: 9 ->  23 Weight: 2 ->  24 Weight: 5 ->  25 Weight: 9 ->  26 Weight: 1 ->  27 Weight: 4 ->  28 Weight: 3 ->  29 Weight: 6 ->  30 Weight: 5 ->  31 Weight: 5 ->  32 Weight: 9 ->  33 Weight: 7 ->  34 Weight: 4 ->  36 Weight: 8 ->  37 Weight: 4 ->  38 Weight: 4 ->  39 Weight: 10 ->  40 Weight: 7 ->  41 Weight: 8 ->  42 Weight: 2 ->  44 Weight: 4 ->  45 Weight: 5 ->  46 Weight: 9 ->  47 Weight: 10 ->  48 Weight: 7 ->  49 Weight: 6 ->  50 Weight: 1 ->  51 Weight: 7 ->  54 Weight: 8 ->  55 Weight: 9 ->  56 Weight: 4 ->  57 Weight: 6 ->  58 Weight: 4 ->  59 Weight: 6
36 ->  1 Weight: 7 ->  2 Weight: 7 ->  3 Weight: 1 ->  4 Weight: 3 

49 ->  1 Weight: 1 ->  2 Weight: 9 ->  3 Weight: 4 ->  4 Weight: 7 ->  6 Weight: 1 ->  7 Weight: 8 ->  8 Weight: 8 ->  9 Weight: 6 ->  10 Weight: 10 ->  12 Weight: 2 ->  13 Weight: 6 ->  14 Weight: 2 ->  15 Weight: 4 ->  16 Weight: 10 ->  17 Weight: 2 ->  18 Weight: 3 ->  19 Weight: 3 ->  20 Weight: 1 ->  21 Weight: 4 ->  22 Weight: 5 ->  23 Weight: 4 ->  24 Weight: 4 ->  25 Weight: 9 ->  27 Weight: 2 ->  28 Weight: 3 ->  29 Weight: 6 ->  30 Weight: 8 ->  31 Weight: 2 ->  34 Weight: 2 ->  35 Weight: 8 ->  36 Weight: 4 ->  37 Weight: 9 ->  39 Weight: 8 ->  40 Weight: 8 ->  41 Weight: 1 ->  43 Weight: 9 ->  44 Weight: 8 ->  45 Weight: 7 ->  46 Weight: 9 ->  47 Weight: 9 ->  48 Weight: 3 ->  51 Weight: 7 ->  52 Weight: 8 ->  53 Weight: 9 ->  55 Weight: 9 ->  56 Weight: 2 ->  57 Weight: 9 ->  58 Weight: 7
50 ->  1 Weight: 9 ->  2 Weight: 10 ->  4 Weight: 5 ->  7 Weight: 1 ->  9 Weight: 5 ->  10 Weight: 10 ->  11 Weight: 8 ->  12 Weight: 9 ->  13 Weight: 9 ->  14 Weight: 2 ->  15 Weight: 2 

Part (a) - Implementation of Dijkstra's algorithm using adjacency matrix + array for priority queue

In [ ]:
class Node():
    
    def __init__(self, vertex, weight):
        self.vertex = vertex
        self.weight = weight

In [ ]:
class PriorityQueue:

    def __init__(self):
        self.q = []

    def insert(self, node):
        if len(self.q) == 0:
            self.q.append(node)
        else:
            for i in range(len(self.q)):
                if node.weight < self.q[i].weight:
                    self.q.insert(i, node)
                    break
                elif node.weight == self.q[i].weight:
                    pass

                if i == len(self.q) - 1:
                    self.q.insert(i + 1, node)

    def getMinNode(self):
        return self.q[0].vertex

    def getMinWeight(self):
        return self.q[0].weight

    def pop(self):
        self.q.pop(0)

    def show(self):
        print("Current priority queue,")
        for i in range(len(self.q)):
            print(self.q[i].vertex, "- Weight", self.q[i].weight)

    def isEmpty(self):
        return len(self.q) == 0

    def removeNode(self, index):
        for i in range(len(self.q)):
            if self.q[i].vertex == index:
                self.q.pop(i)
                break

In [ ]:
def DijkstraA(G, source):
    time_start = timeit.default_timer()
    
    distance = [sys.maxsize] * G.V  # Original distance for all vertices are set to infinity
    path = [[] for i in range(G.V)]  # Initialize N number of sub-lists to store the path to each node
    S = [False] * G.V  # Initialize False to all the nodes since shortest path not yet discovered

    distance[source] = 0  # Set distance of source node to be zero
    pQueue = PriorityQueue()

    for i in range(G.V):  # Insert all the vertices into priority queue
        tempNode = Node(i, distance[i])
        pQueue.insert(tempNode)

    while (not pQueue.isEmpty()):
        u = pQueue.getMinNode()
        pQueue.pop()
        S[u] = True

        for i in range(G.V):
            if G.matrixgraph[u][i] != 0:
                if S[i] != True and distance[i] > distance[u] + G.matrixgraph[u][i]:
                    pQueue.removeNode(i)
                    distance[i] = distance[u] + G.matrixgraph[u][i]                   
                    if source not in path[i]:
                        for elements in path[u]:
                            path[i].append(elements)
                    path[i].append(u)
                    pQueue.insert(Node(i, distance[i]))
    
    time_stop = timeit.default_timer()
    #END OF DIJKSTRA ALGORITHM
    
    #Print results
    print("Time elapsed for program: ", (time_stop - time_start)*1000, "milliseconds")  # Time in milliseconds
    print("Distance from source node,")
    for i in range(0, G.V):
        if distance[i] == sys.maxsize:
            print("Source to node", i, ": No such path exist")
        else:
            print("Source to node", i, ":", distance[i])
        resultA.append(distance[i])
    
    print()
    print("Path to get to each node,")
    
    for i in range(0, G.V):
        print("Path from source to node", i)
        print(path[i])
        print()

In [ ]:
DijkstraA(g, 0)

Part (b) - Implementation of Dijkstra's algorithm using adjacency list + min heap as priority queue

For this implementation, we shall use the heapq module for our min heap.

In [ ]:
def DijkstraB(G, source):
    time_start = timeit.default_timer()
    
    distance = [sys.maxsize] * G.V  # Original distance for all vertices are set to infinity
    path = [[] for i in range(G.V)]  # Initialize N number of sub-lists to store the path to each node
    S = [False] * G.V  # Initialize False to all the nodes since shortest path not yet discovered

    distance[source] = 0  # Set distance of source node to be zero
    
    minHeap = []
    for i in range(G.V):  # Insert all the vertices into min heap
        heapq.heappush(minHeap, [distance[i], i])
    
    while (len(minHeap) != 0):
        u = heapq.heappop(minHeap)
        S[u[1]] = True
        
        for elements in G.listgraph[u[1]]:
            if S[elements[0]] != True and distance[elements[0]] > distance[u[1]] + elements[1]:
                for z in minHeap:
                    if z[1] == elements[0]:
                        minHeap.remove(z)
                        heapq.heapify(minHeap)
                            
                distance[elements[0]] = distance[u[1]] + elements[1]
                    
                if source not in path[elements[0]]:
                    for nodes in path[u[1]]:
                        path[elements[0]].append(nodes)
                path[elements[0]].append(u[1])
                    
                heapq.heappush(minHeap, [distance[elements[0]], elements[0]])
    
    time_stop = timeit.default_timer()
    #END OF DIJKSTRA ALGORITHM
    
    #Print results
    print("Time elapsed for program: ", (time_stop - time_start)*1000, "milliseconds")  # Time in milliseconds
    print("Distance from source node,")
    for i in range(0, G.V):
        if distance[i] == sys.maxsize:
            print("Source to node", i, ": No such path exist")
        else:
            print("Source to node", i, ":", distance[i])
        resultB.append(distance[i])
    
    print()
    print("Path to get to each node,")
    
    for i in range(0, G.V):
        print("Path from source to node", i)
        print(path[i])
        print()

In [ ]:
DijkstraB(g, 0)

Comparing the results of the 2 variations to see if they match

In [ ]:
Error = False

for i in range(len(resultA)):
    if resultA[i] == resultB[i]:
        continue
    else:
        Error = True
        break
        
if (Error):
    print("Something went wrong")
    for i in range(len(resultA)):
        print("Node", i, resultA[i] == resultB[i])
else:
    print("Output for both variations are the same")